services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" # Porta para acessar a API S3
      - "9090:9090" # Porta para acessar o painel administrativo
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9090"
    deploy:
      resources:
        limits:
          memory: 2g        
          cpus: "1.0"       
        reservations:
          memory: 512m 
volumes:
  minio_data:
    driver: local